### PR TITLE
Add the various sentiment score  type to the analytics query

### PR DESCRIPTION
**Pull request by tobianointing**
added positive, negative, and neutral sentiment count to twitter and reddit analytics query

### CODE REVIEW

**Comment by E-STAT** [comment]
Hey @tobianointing 

Thanks for the PR. Please, check the main.py file and revert it to its default state. 

You can check the current main for reference.

**Comment by tobianointing** [comment]
Alright I will do that right away

**Comment by tobianointing** [comment]
Alright I will do that right away

**Comment by tobianointing** [comment]
Alright I will do that right away

**Comment by tobianointing** [comment]
Alright I will right away

**Review by E-STAT — APPROVED** [review]

**Pull request merged**
